# Configuración para el entorno de Producción (prod)

# H2 Console (Deshabilitado por seguridad en producción)
spring.h2.console.enabled=false

# Datasource: Base de datos guardada en un archivo local (Persistente)
spring.datasource.url=jdbc:h2:file:./data/study_prod_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=secure_prod_password

# JPA/Hibernate: No mostrar consultas SQL en consola en producción por rendimiento
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
